name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download cmocka
      run: curl https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz --output cmocka-1.1.5.tar.xz --silent
    - name: uncompress cmocka
      run: xz -d cmocka-1.1.5.tar.xz && tar vxf cmocka-1.1.5.tar
    - name: install cmocka
      run: (cd cmocka-1.1.5 && mkdir build && cd $_ && cmake -DCMAKE_BUILD_TYPE=Release .. && make && sudo make install)
    - name: Cache Compiled code
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-compiled
        path: |
          ./obj
    - name: make
      run: make

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download cmocka
      run: curl https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz --output cmocka-1.1.5.tar.xz --silent
    - name: uncompress cmocka
      run: xz -d cmocka-1.1.5.tar.xz && tar vxf cmocka-1.1.5.tar
    - name: install cmocka
      run: (cd cmocka-1.1.5 && mkdir build && cd $_ && cmake -DCMAKE_BUILD_TYPE=Release .. && make && sudo make install)
    - name: Cache Compiled code
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-compiled
        path: |
          ./obj
    - name: make run_test
      run: export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH} && make run_test

