name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: execb5/chip8-builder:latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Compiled code
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-compiled
        path: |
          ./obj
    - name: make
      run: make

  test:

    needs: build

    runs-on: ubuntu-latest
    container:
      image: execb5/chip8-builder:latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Compiled code
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-compiled
        path: |
          ./obj
    - name: make run_test
      run: export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH} && make run_test

